### ISSUE TITLE
Gaussian

### ISSUE THREAD

**Issue by ibmua** [ducha-aiki/LSUVinit#4]
What Caffe-side initialization to use before running LSUV, or Ortho script? I saw Gaussian in most of the benchmarks, but I stumbled upon Xavier https://github.com/ducha-aiki/caffenet-benchmark/blob/master/prototxt/architectures/SqueezeNet128_lsuv.prototxt just now.

**Comment by ducha-aiki** [comment]
Doesn`t matter for Ortho or OrthoLSUV - first it fills everything with ortho.
For LSUV itself, the best pre-fill is ortho, 2nd - Gaussian
