### ISSUE TITLE
Cannot proceed layer [loss] skiping

### ISSUE THREAD

**Issue by ibmua** [ducha-aiki/LSUVinit#5]
I'm getting a 
"Cannot proceed layer loss4 skiping"
message, which, as far as I understand, is usual, but very confusing. If the warning is not really about a problem, it's a very good idea to write something non-scary in such cases instead.

**Comment by ducha-aiki** [comment]
Fixed by https://github.com/ducha-aiki/LSUVinit/commit/462c8f47728a66605be8ec4817230cbbbf0629bf
