### ISSUE TITLE
question about "scale your input to var=1 before applying LSUV"

### ISSUE THREAD

**Issue by xuanzhaopeng** [ducha-aiki/LSUVinit#8]
Hi, I read your examples cifar10 and cifar 100, I never see you scale the input.

So could you clarify the steps in caffe  "scale your input to var=1 before applying LSUV" in detail?

If I use mean file, should I still use scale in transform parameter?

Thanks

**Comment by ducha-aiki** [comment]
@xuanzhaopeng it is simple - lmdbs with CIFAR-10 images already contain scaled and whitened images, unlike MNIST or ImageNet. That is why I haven`t used scale in CIFAR-10/100.

By scaling I mean: 1) calculate std of the training set 2) add 1/std as a scale to the transform param.

If you use mean file, you still need to scale. E.g. in imagenet you have images [0..255]. After using mean file you will have smth like [-127..127]. So scale is still needed. 
See  an example here: https://github.com/ducha-aiki/caffenet-benchmark/blob/master/prototxt/caffenet128_lsuv.prototxt#L29
